name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  security-and-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Dependency Check
        # Uses standard npm audit to check for vulnerable packages
        run: npm audit --audit-level=moderate || true 

      - name: Spin up Infrastructure (Integration)
        # Starts your Postgres DB and Node App in the background
        run: docker-compose up -d

      - name: Wait for Services to Boot
        # Pauses the pipeline for 10 seconds to ensure the database and web app are fully ready
        run: sleep 10

      - name: Run UI Testing over HTTP
        # Executes the Mocha/Selenium test against localhost:8080
        run: npm test